import type { Metadata } from 'next'
import './global.css'
import { Inter } from 'next/font/google'
import logoImg from '../assets/logoImg.svg'
import Image from 'next/image'
import {GlobalStyle, Container, Header } from '../styles/pages/homeBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
       <body>
        <GlobalStyle />
        <Container>
          <Header>
            <Image src={logoImg} alt="logo" />
          </Header>
          {children}
        </Container>
      </body>
    </html>
  )
}
